name: Publish to NPM
on:
  push:
    branches:
      - production

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing to NPM..."
          sudo npm install -g pnpm

          pnpm install
          pnpm run build
          pnpm publish --access public --no-git-checks
